### ISSUE TITLE
Please help publish version 1.0.0

### ISSUE THREAD

**Issue by cula** [log4js-node/streamroller#18]
@nomiddlename  thx

**Comment by nomiddlename** [comment]
Thanks for working on this. Just a couple of things - first one is to try not to push directly to master. Create a branch, make all your changes on the branch, then create a PR for the changes. You can merge it yourself, it just makes it easier to see all the changes in one place rather than having to go back through commit history. 

The comment for one of the commits says "refactor: support node v4" - but it looks like the babel config is for node v6 as a minimum. I haven't used babel much, so maybe I got that wrong. Also the readme says that node v4 is not supported in v1.0.0+. I thought your plan was to add in node v4 support using babel?

**Comment by cula** [comment]
@nomiddlename 
1. I couldn't agree more! I've rollbacked the master and created a [pull rquest](https://github.com/log4js-node/streamroller/pull/19).  I'm sorry for pushing it directly last time.

2. "refactor: support node v4" is one of the commit. I tried to make it in version 0.8.1 but I found it needed some extra work. So I aborted and jumped to version 1.x which is not aimed to support node v4. So some files are labeled with this commit message. 

But now, I've done the extra work in the pull request. So please make a check.
The version is 0.8.1 instead of 1.0.0. I'll make another pull request for 1.0.0 as soon as this passes.

**Comment by nomiddlename** [comment]
No problem. So the change I just merged is ready to be published to NPM as version 0.8.1, right?

**Comment by cula** [comment]
yes!

**Comment by nomiddlename** [comment]
Done!
